- hosts: gateway
  tasks:
    - name: ensure nginx is at the latest version
      apt:
        name: nginx
        state: latest
        update_cache: yes
      become: yes

    - name: start nginx
      service:
        name: nginx
        state: started
      become: yes

    - name: copy the nginx config wayshub
      copy:
        src: /home/ubuntu/ansible/gateway/reverse-proxy-wayshub.conf
        dest: /etc/nginx/sites-enabled/reverse-proxy-wayshub.conf
      become: yes

    - name: copy the nginx config prometheus
      copy:
        src: /home/ubuntu/ansible/gateway/reverse-proxy-prometheus.conf
        dest: /etc/nginx/sites-enabled/reverse-proxy-prometheus.conf
      become: yes        

    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes

    - name: Install Certbot with Snap
      snap:
        name: certbot
        classic: yes
        state: present
      become: yes

    - name: Obtain and install SSL certificate with Certbot Nginx wayshub
      command: certbot --nginx -d salman.studentdumbways.my.id --non-interactive --agree-tos --email sallfarr@outlook.com
      become: yes

    - name: Obtain and install SSL certificate with Certbot Nginx prometheus
      command: certbot --nginx -d prometheus.salman.studentdumbways.my.id --non-interactive --agree-tos --email sallfarr@outlook.com
      become: yes       

    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes
