---
- name: Deploy Monitoring Stack
  hosts: monitoring
  become: true
  tasks:
    - name: Pull bitnami/prometheus Docker image
      docker_image:
        name: bitnami/prometheus
        source: pull

    - name: Pull grafana/grafana Docker image
      docker_image:
        name: grafana/grafana
        source: pull

    - name: Create directories for Prometheus
      file:
        path: /home/salman/prometheus/
        state: directory
        mode: "0755"

    - name: Copy prometheus.yml configuration file
      copy:
        src: /home/ubuntu/ansible/storehouse/prometheus.yml
        dest: /home/salman/prometheus/prometheus.yml
        mode: "0644"

    - name: Run Prometheus container
      docker_container:
        name: prom
        image: bitnami/prometheus
        state: started
        restart_policy: always
        ports:
          - "9090:9090"
        volumes:
          - "/home/salman/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

    - name: Run Grafana container
      docker_container:
        name: dashboard
        image: grafana/grafana
        state: started
        restart_policy: always
        ports:
          - "3000:3000"

